target-version = "py314"
line-length = 88
indent-width = 4

[format]
preview = false
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false
docstring-code-format = true

[lint]
preview = false
select = [
  "E",   # pycodestyle error
  "W",   # pycodestyle warn
  "F",   # pyflakes
  "I",   # isort
  "N",   # pep8-naming
  "B",   # flake8-bugbear
  "SIM", # flake8-simplify
  "UP",  # pyupgrade-up
]

[lint.per-file-ignores]
"__init__.py" = ["F401"]

